gui:
  scrollHeight: 5
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --24-bit-color=never --line-numbers
  overrideGpg: true
os:
    openCommand: "ttab 'vim {{filename}}'"
